In [1]:
import pymongo
from pymongo import MongoClient

In [2]:
client = MongoClient("mongodb://10.176.58.101:27777/")

In [10]:
databases = client.list_database_names()
print("Databases:", databases)

Databases: ['admin', 'config', 'local', 'mamba', 'mechinterp', 'pythia', 'test', 'test_database']


In [11]:
db = client['mechinterp']
collections = db.list_collection_names()
print("Collections in", 'mechinterp', ":", collections)

Collections in mechinterp : ['fs.files', 'features', 'dictionaries', 'fs.chunks', 'attn_heads']


In [41]:
collection_name = "dictionaries"
# Replace with your collection name
collection = db[collection_name]

stats = db.command("collstats", collection_name)
print("Collection stats for", collection_name, ":", stats)
documents = collection.find()
time = 0
series_type = []
for doc in documents:
    print(doc)
    break
    if doc['series'] not in series_type:
        series_type.append(doc['series'])
    # time += 1

print("Series type:", series_type)

Collection stats for dictionaries : {'ns': 'mechinterp.dictionaries', 'size': 25858, 'count': 292, 'avgObjSize': 88, 'numOrphanDocs': 0, 'storageSize': 45056, 'freeStorageSize': 20480, 'capped': False, 'wiredTiger': {'metadata': {'formatVersion': 1}, 'creationString': 'access_pattern_hint=none,allocation_size=4KB,app_metadata=(formatVersion=1),assert=(commit_timestamp=none,durable_timestamp=none,read_timestamp=none,write_timestamp=off),block_allocation=best,block_compressor=snappy,cache_resident=false,checksum=on,colgroups=,collator=,columns=,dictionary=0,encryption=(keyid=,name=),exclusive=false,extractor=,format=btree,huffman_key=,huffman_value=,ignore_in_memory_cache_size=false,immutable=false,import=(compare_timestamp=oldest_timestamp,enabled=false,file_metadata=,metadata_file=,repair=false),internal_item_max=0,internal_key_max=0,internal_key_truncate=true,internal_page_max=4KB,key_format=q,key_gap=10,leaf_item_max=0,leaf_key_max=0,leaf_page_max=32KB,leaf_value_max=64MB,log=(enable

In [34]:
import base64
import numpy as np
from bson import Binary
from io import BytesIO
# The base64 string extracted from MongoDB
# base64_string = 'k05VTVBZAQB2AHsnZGVzY3InOiAnPGY4JywgJ2ZvcnRyYW5fb3JkZXInOiBGYWxzZSwgJ3NoYXBlJzogKDIwLCAyNTYpLCB9ICAg'

# Decode the base64 string to binary data
# binary_data = base64.b64decode(base64_string)

# Deserialize the binary data to a NumPy array
# Use BytesIO to create a file-like object from the binary data
file_like = BytesIO(binary_data)

# Load the NumPy array from the file-like object
numpy_array = np.load(file_like)

print("Deserialized NumPy array:")
print(numpy_array)
numpy_array.shape

Deserialized NumPy array:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


(20, 256)